name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y lcov

      - name: Configure CMake
        working-directory: ./banking
        run: |
          cmake -H. -B_build -DBUILD_TESTS=ON

      - name: Build project
        working-directory: ./banking
        run: |
          cmake --build _build

      - name: Run tests
        working-directory: ./banking
        run: |
          cd _build && ctest --output-on-failure

      - name: Generate coverage report
        working-directory: ./banking
        run: |
        
          cd _build
          lcov --capture --directory . --output-file coverage.info
          lcov --remove coverage.info '/usr/*' --output-file coverage.info
          lcov --list coverage.info

      - name: Upload to Coveralls
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: _build/coverage.info
